dataset: deep-conus
dataset_args: {split: test, root_path: /fs/nexus-scratch/rhaworth/deep-conus/data-future/, timestamp: 1716491090.024492}

load_encoder: ./save/classifier_deep-conus_resnet12/epoch-last.pth