dataset: deep-conus
dataset_args: {split: test, root_path: ../deep-conus/data-future/}

load: ./save/meta_deep-conus-1shot_meta-baseline-resnet12/max-va.pth
# load_encoder: ./save/classifier_deep-conus_resnet12/epoch-last.pth

# Replace load with load_encoder for loading the encoder only (e.g. for testing Classifier-Baseline)