train_dataset: deep-conus
train_dataset_args: {split: train, root_path: ../deep-conus/data/}
fs_dataset: deep-conus
fs_dataset_args: {split: test, root_path: ../deep-conus/data-future/}
eval_fs_epoch: 5

model: classifier
model_args:
    encoder: resnet12
    encoder_args: {}
    classifier: linear-classifier 
    classifier_args: {n_classes: 10}

batch_size: 128
max_epoch: 100
optimizer: sgd
optimizer_args: {lr: 0.1, weight_decay: 5.e-4, milestones: [30,60,90]}

save_epoch: 5
visualize_datasets: false
