train_dataset: deep-conus
train_dataset_args: {split: train, root_path: /fs/nexus-scratch/rhaworth/deep-conus/current/, timestamp: 1716492963.5225127}
tval_dataset: deep-conus
tval_dataset_args: {split: test, root_path: /fs/nexus-scratch/rhaworth/deep-conus/future/, timestamp: 1716492963.5225127}
val_dataset: deep-conus
val_dataset_args: {split: val, root_path: /fs/nexus-scratch/rhaworth/deep-conus/current/, timestamp: 1716492963.5225127}

model: meta-baseline
model_args: 
    encoder: resnet12
    encoder_args: {}
load_encoder: ./save/classifier_deep-conus_resnet12/epoch-last.pth

n_way: 5
n_shot: 1
n_query: 15
train_batches: 200
ep_per_batch: 4

max_epoch: 20
optimizer: sgd
optimizer_args: {lr: 0.0001, weight_decay: 5.e-5}

visualize_datasets: False
